<?php
$this->breadcrumbs=array(
	'Matriculas'=>array('index'),
	$model->nmatricula,
);

$this->menu=array(
	array('label'=>'Listar Matriculas', 'url'=>array('index')),
	/*array('label'=>'Criar Matriculas', 'url'=>array('create')),*/
	array('label'=>'Editar Matriculas', 'url'=>array('update', 'id'=>$model->nmatricula)),
	array('label'=>'Gerir Matriculas', 'url'=>array('admin')),
);
?>

<h1>Detalhes Matriculas #<?php echo $model->nmatricula; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'nmatricula',
		'ano_a_se_inscreve',
		'lista_cursos',
		'lista_opcao_b',
		'lista_opcao_c',
		'moral',
		'saida',
		'erenovacaomatricula',
		'estabelecimento',
		'ano',
		'anolectivode',
		'escola',
		'campos_extra1',
		'campos_extra2',
		'campos_extra3',
		'campos_extra4',
		'transporte',
		'embarque',
		'nomecompleto',
		'nacionalidade',
		'naturaldafreguesia',
		'concelho',
		'distrito',
		'datanasc',
		'bi',
		'segsocial',
		'email',
		'residente',
		'localidade',
		'codpostal',
		'telefone',
		'filhoA',
		'profissaoA',
		'filhoB',
		'profissaoB',
		'nomecompletoee',
		'profissaoee',
		'residenteee',
		'localidadeee',
		'codpostalee',
		'telefoneresidenciaee',
		'telefonetrabalhoee',
		'parentescoee',
		'ultimoanolectivo',
		'ultimoanoescolaridade',
		'ultimoanoturma',
		'ultimoanocurso',
		'ultimoanoescola',
		'apoioespecial',
		'precisaapoioespecial',
		'estrangeira',
		'estrangeiraa',
		'estrangeiraaa',
		'disciplinas_melhoria',
		'disciplinas_em_atraso',
		'observacoes',
		'identificacao_fiscal',
		'utente_saude',
		'abono',
		'vacinas',
		'n_cartao_estudante',
		'observacoes_internas',
		'activa',
		'paga',
		'processada',
		'paga',
		'gerarreferenciamultibanco',
	),
)); ?>
